services:
  - type: web
    name: gel-stock-api
    env: php
    buildCommand: echo "GEL-STOCK API"
    startCommand: cd api && php -S 0.0.0.0:10000
    envVars:
      - key: DB_HOST
        value: dpg-d4ictcjqkflc73b4e3b0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: gelstockdb
      - key: DB_USER
        value: gelstockdb_user
      - key: DB_PASS
        value: 4y8yiyVYLXlWRtDHj107hE2xgRe0Qe3A
      - key: CORS_ENABLED
        value: "true"
      - key: API_MODE
        value: production

databases:
  - name: gel-stock-db
    engine: postgresql
    version: "15"
